// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Context;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TaskManagementDbContext))]
    [Migration("20231221173619_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04d46ab1-6a8c-472a-ae76-22f1317482ea"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(892),
                            IsDeleted = "0",
                            Name = "PAM",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(911)
                        },
                        new
                        {
                            Id = new Guid("ddb5b087-3378-463b-bb54-69685fc1c302"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1060),
                            IsDeleted = "0",
                            Name = "DBA",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1062)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CellPhone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("CuitCuil")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Legajo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db4e1272-4529-4af8-8778-67ed387aa18f"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(959),
                            DateOfBirth = new DateTime(1991, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("04d46ab1-6a8c-472a-ae76-22f1317482ea"),
                            DocumentNumber = "36192398",
                            Email = "i.ressel@ptytechnologies.com",
                            EnrollmentDate = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = "0",
                            Name = "ISMAIN",
                            Surname = "RESSEL",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(964)
                        },
                        new
                        {
                            Id = new Guid("47bcc4af-9a09-4cb8-875f-0f3195a83ece"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1073),
                            DateOfBirth = new DateTime(1991, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("ddb5b087-3378-463b-bb54-69685fc1c302"),
                            DocumentNumber = "36185222",
                            Email = "g.prado@ptytechnologies.com",
                            EnrollmentDate = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = "0",
                            Name = "GONZALO",
                            Surname = "PRADO",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1075)
                        },
                        new
                        {
                            Id = new Guid("99c96d0d-5494-461b-9f3e-868e1d0476e1"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1101),
                            DateOfBirth = new DateTime(1994, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("ddb5b087-3378-463b-bb54-69685fc1c302"),
                            DocumentNumber = "38111222",
                            Email = "c.guelpa@ptytechnologies.com",
                            EnrollmentDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = "0",
                            Name = "CARLA",
                            Surname = "GUELPA",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1103)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b0a97ab-abe2-49e4-81af-b4e9a03f167a"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1033),
                            DeliveryDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implementar Customer Emails",
                            EmployeeId = new Guid("db4e1272-4529-4af8-8778-67ed387aa18f"),
                            IsDeleted = "0",
                            Status = 5,
                            Title = "PSS-1",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1034)
                        },
                        new
                        {
                            Id = new Guid("284bccf2-a08f-49b5-b96f-df5f53affca4"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1047),
                            DeliveryDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explicar EF",
                            EmployeeId = new Guid("db4e1272-4529-4af8-8778-67ed387aa18f"),
                            IsDeleted = "0",
                            Status = 1,
                            Title = "PSS-2",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1048)
                        },
                        new
                        {
                            Id = new Guid("7dc684cc-d773-408b-a98b-57a192fbfd51"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1130),
                            DeliveryDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a PSS",
                            EmployeeId = new Guid("47bcc4af-9a09-4cb8-875f-0f3195a83ece"),
                            IsDeleted = "0",
                            Status = 5,
                            Title = "DBA-1",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1131)
                        },
                        new
                        {
                            Id = new Guid("cef687c3-16f7-495a-b759-78e2d06571e5"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1143),
                            DeliveryDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a Cashier",
                            EmployeeId = new Guid("47bcc4af-9a09-4cb8-875f-0f3195a83ece"),
                            IsDeleted = "0",
                            Status = 1,
                            Title = "DBA-2",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1144)
                        },
                        new
                        {
                            Id = new Guid("bf40bf09-0b6b-4e6d-9353-93d823e9dbc3"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1154),
                            DeliveryDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a PSS",
                            EmployeeId = new Guid("99c96d0d-5494-461b-9f3e-868e1d0476e1"),
                            IsDeleted = "0",
                            Status = 5,
                            Title = "DBA-3",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1155)
                        },
                        new
                        {
                            Id = new Guid("59713339-b293-43ac-98fe-1592dff9ffa8"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1213),
                            DeliveryDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a PSS",
                            EmployeeId = new Guid("99c96d0d-5494-461b-9f3e-868e1d0476e1"),
                            IsDeleted = "0",
                            Status = 1,
                            Title = "DBA-4",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1214)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.PersonAggregate.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("DepartmentLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailedAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<bool?>("IsOnTheGroundFloor")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88942c25-7165-4bfd-9cc1-3c88227035dd"),
                            AddressNumber = "1440",
                            City = "La Plata",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(995),
                            DepartmentLetter = "A",
                            DepartmentNumber = "2",
                            DetailedAddress = "Calle 16 1440 e/ 61 y 62 2A",
                            EmployeeId = new Guid("db4e1272-4529-4af8-8778-67ed387aa18f"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = false,
                            State = "BA",
                            Street = "16",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(996),
                            ZipCode = "1900"
                        },
                        new
                        {
                            Id = new Guid("aa789cd9-7c5e-4d8b-bcda-7d964a00442e"),
                            AddressNumber = "225",
                            City = "Carmen de Patagones",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1016),
                            DetailedAddress = "Harosteguy 225, Casa",
                            EmployeeId = new Guid("db4e1272-4529-4af8-8778-67ed387aa18f"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = true,
                            State = "BA",
                            Street = "Harosteguy",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1017),
                            ZipCode = "8504"
                        },
                        new
                        {
                            Id = new Guid("a9bfd441-b7cc-47b0-9064-63543e2ce478"),
                            AddressNumber = "1953",
                            City = "Mendoza",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1088),
                            DetailedAddress = "Perón 1953, casa",
                            EmployeeId = new Guid("47bcc4af-9a09-4cb8-875f-0f3195a83ece"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = true,
                            State = "MZA",
                            Street = "Perón",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1089),
                            ZipCode = "M5500"
                        },
                        new
                        {
                            Id = new Guid("9c45b55b-58f8-402a-8b35-93e22148e1c6"),
                            AddressNumber = "442",
                            City = "Buenos Aires",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1117),
                            DepartmentLetter = "B",
                            DepartmentNumber = "7",
                            DetailedAddress = "Alem 442 7B",
                            EmployeeId = new Guid("99c96d0d-5494-461b-9f3e-868e1d0476e1"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = false,
                            State = "BA",
                            Street = "ALEM",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 36, 19, 42, DateTimeKind.Local).AddTicks(1118),
                            ZipCode = "B1228"
                        });
                });

            modelBuilder.Entity("TaskManagement.Infrastructure.Context.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Flgeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Comment", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", "Employee")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.PersonAggregate.Address", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", "Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
