// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Context;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TaskManagementDbContext))]
    partial class TaskManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d52369ec-b118-425d-887a-b708e09e940b"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7026),
                            IsDeleted = "0",
                            Name = "PAM",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7048)
                        },
                        new
                        {
                            Id = new Guid("59247211-fdcf-4ac1-959d-1403e2340439"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7189),
                            IsDeleted = "0",
                            Name = "DBA",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7190)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CellPhone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("CuitCuil")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Lastname")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Legajo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e478fc7-a10e-4ef1-907b-f7cd5cdcb748"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7094),
                            DateOfBirth = new DateTime(1991, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("d52369ec-b118-425d-887a-b708e09e940b"),
                            DocumentNumber = "36192398",
                            Email = "i.ressel@ptytechnologies.com",
                            EnrollmentDate = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = "0",
                            Lastname = "RESSEL",
                            Name = "ISMAIN",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7097)
                        },
                        new
                        {
                            Id = new Guid("35e4951b-6dde-4131-9dae-9554bba3a275"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7202),
                            DateOfBirth = new DateTime(1991, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("59247211-fdcf-4ac1-959d-1403e2340439"),
                            DocumentNumber = "36185222",
                            Email = "g.prado@ptytechnologies.com",
                            EnrollmentDate = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = "0",
                            Lastname = "PRADO",
                            Name = "GONZALO",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7203)
                        },
                        new
                        {
                            Id = new Guid("0b647439-c2a2-4ade-a880-61cf4da91a47"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7231),
                            DateOfBirth = new DateTime(1994, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("59247211-fdcf-4ac1-959d-1403e2340439"),
                            DocumentNumber = "38111222",
                            Email = "c.guelpa@ptytechnologies.com",
                            EnrollmentDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = "0",
                            Lastname = "GUELPA",
                            Name = "CARLA",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7233)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Subtask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8575100-a6ae-4f36-84be-5f3516c29b60"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7159),
                            DeliveryDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implementar Customer Emails",
                            EmployeeId = new Guid("4e478fc7-a10e-4ef1-907b-f7cd5cdcb748"),
                            IsDeleted = "0",
                            Status = 5,
                            Title = "PSS-1",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7160)
                        },
                        new
                        {
                            Id = new Guid("889c48d4-8010-4e06-949d-413d3dab4e06"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7175),
                            DeliveryDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explicar EF",
                            EmployeeId = new Guid("4e478fc7-a10e-4ef1-907b-f7cd5cdcb748"),
                            IsDeleted = "0",
                            Status = 1,
                            Title = "PSS-2",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7176)
                        },
                        new
                        {
                            Id = new Guid("4c4eab77-e0e2-4686-b991-d0c610e1066e"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7260),
                            DeliveryDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a PSS",
                            EmployeeId = new Guid("35e4951b-6dde-4131-9dae-9554bba3a275"),
                            IsDeleted = "0",
                            Status = 5,
                            Title = "DBA-1",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7262)
                        },
                        new
                        {
                            Id = new Guid("2b6eb53e-4356-4c99-ac92-e56b578c98c4"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7273),
                            DeliveryDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a Cashier",
                            EmployeeId = new Guid("35e4951b-6dde-4131-9dae-9554bba3a275"),
                            IsDeleted = "0",
                            Status = 1,
                            Title = "DBA-2",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7274)
                        },
                        new
                        {
                            Id = new Guid("0473df39-6a32-45c9-bb6c-67949f03cf2b"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7285),
                            DeliveryDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a PSS",
                            EmployeeId = new Guid("0b647439-c2a2-4ade-a880-61cf4da91a47"),
                            IsDeleted = "0",
                            Status = 5,
                            Title = "DBA-3",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7286)
                        },
                        new
                        {
                            Id = new Guid("0a5dc042-a7b9-4f95-83bc-3f5d7930a12e"),
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7300),
                            DeliveryDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soporte a PSS",
                            EmployeeId = new Guid("0b647439-c2a2-4ade-a880-61cf4da91a47"),
                            IsDeleted = "0",
                            Status = 1,
                            Title = "DBA-4",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7301)
                        });
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.PersonAggregate.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("createddate");

                    b.Property<string>("DepartmentLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailedAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("isdeleted");

                    b.Property<bool?>("IsOnTheGroundFloor")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updatedby");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("updateddate");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f02d124-6926-49d8-ac0a-fbe50502b6e1"),
                            AddressNumber = "1440",
                            City = "La Plata",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7121),
                            DepartmentLetter = "A",
                            DepartmentNumber = "2",
                            DetailedAddress = "Calle 16 1440 e/ 61 y 62 2A",
                            EmployeeId = new Guid("4e478fc7-a10e-4ef1-907b-f7cd5cdcb748"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = false,
                            State = "BA",
                            Street = "16",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7122),
                            ZipCode = "1900"
                        },
                        new
                        {
                            Id = new Guid("0411c24b-94ed-4a5f-9ffb-361867eba6ac"),
                            AddressNumber = "225",
                            City = "Carmen de Patagones",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7140),
                            DetailedAddress = "Harosteguy 225, Casa",
                            EmployeeId = new Guid("4e478fc7-a10e-4ef1-907b-f7cd5cdcb748"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = true,
                            State = "BA",
                            Street = "Harosteguy",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7141),
                            ZipCode = "8504"
                        },
                        new
                        {
                            Id = new Guid("05a50481-aa73-4190-a5b7-9755436029d2"),
                            AddressNumber = "1953",
                            City = "Mendoza",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7216),
                            DetailedAddress = "Perón 1953, casa",
                            EmployeeId = new Guid("35e4951b-6dde-4131-9dae-9554bba3a275"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = true,
                            State = "MZA",
                            Street = "Perón",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7217),
                            ZipCode = "M5500"
                        },
                        new
                        {
                            Id = new Guid("8711cd61-e600-48a3-bc33-71645c9523dd"),
                            AddressNumber = "442",
                            City = "Buenos Aires",
                            Country = "Argentina",
                            CreatedBy = "iressel",
                            CreatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7246),
                            DepartmentLetter = "B",
                            DepartmentNumber = "7",
                            DetailedAddress = "Alem 442 7B",
                            EmployeeId = new Guid("0b647439-c2a2-4ade-a880-61cf4da91a47"),
                            IsDeleted = "0",
                            IsOnTheGroundFloor = false,
                            State = "BA",
                            Street = "ALEM",
                            UpdatedBy = "iressel",
                            UpdatedDate = new DateTime(2023, 12, 21, 14, 47, 0, 558, DateTimeKind.Local).AddTicks(7247),
                            ZipCode = "B1228"
                        });
                });

            modelBuilder.Entity("TaskManagement.Infrastructure.Context.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Flgeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TaskManagement.Infrastructure.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Comment", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Subtask", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", "Ticket")
                        .WithMany("Subtasks")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", "Employee")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.PersonAggregate.Address", b =>
                {
                    b.HasOne("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", "Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Employee", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TaskManagement.Domain.Aggregates.DepartmentAggregate.Ticket", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
